/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg603_assignment2;


import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;


/**
 *
 * @author Monalisa
 */
public class TravelApp extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */

    public TravelApp()
    {  this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setSize(500,350);
        this.setLocationRelativeTo(null);
        initComponents();
        this.setVisible(true);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.  
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RestartButton = new javax.swing.JButton();
        exitButton1 = new javax.swing.JButton();
        ptaxiRB = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dateBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        monthbox = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        yearBox = new javax.swing.JComboBox<>();
        year = new javax.swing.JLabel();
        peopleField = new javax.swing.JTextField();
        BusRB = new javax.swing.JRadioButton();
        trainRB = new javax.swing.JRadioButton();
        ferryRB = new javax.swing.JRadioButton();
        taxiRB = new javax.swing.JRadioButton();
        premiumTaxiRB = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        hamiltonRB = new javax.swing.JRadioButton();
        RotoruaRB = new javax.swing.JRadioButton();
        NapierRB = new javax.swing.JRadioButton();
        WellingtonRB = new javax.swing.JRadioButton();
        confirmstep2 = new javax.swing.JButton();
        TotalField = new javax.swing.JLabel();
        totalCost = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        phoneField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        ageField = new javax.swing.JTextField();
        confirmstep1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel20 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        visaRB = new javax.swing.JRadioButton();
        mastercardRB = new javax.swing.JRadioButton();
        aeRB = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        cardNumberField = new javax.swing.JTextField();
        cardholdersnameField = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        cardMM = new javax.swing.JComboBox<>();
        cardYear = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        cvvField = new javax.swing.JPasswordField();
        confirmstep3 = new javax.swing.JButton();
        cvvHelp = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel1.setFont(new java.awt.Font("Myanmar MN", 0, 36)); // NOI18N
        jLabel1.setText("Welcome to I Book A Ride!");

        RestartButton.setBackground(new java.awt.Color(255, 204, 255));
        RestartButton.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        RestartButton.setText("Restart");
        RestartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestartButtonActionPerformed(evt);
            }
        });

        exitButton1.setBackground(new java.awt.Color(255, 204, 255));
        exitButton1.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        exitButton1.setText("EXIT");
        exitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RestartButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(421, 421, 421))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(1221, Short.MAX_VALUE)
                    .addComponent(exitButton1)
                    .addGap(16, 16, 16)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(RestartButton)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(exitButton1)
                    .addContainerGap(37, Short.MAX_VALUE)))
        );

        ptaxiRB.setBackground(new java.awt.Color(255, 255, 255));
        ptaxiRB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel2.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel2.setText("Select your mode of transport, if you would like to ride in Auckland:");

        jLabel9.setText("Please enter the number of people: (0-200): ");

        jLabel10.setText("Please enter the date of travel (currently taking booking through to 2025): ");

        dateBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dateBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datePerfomed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        jLabel11.setText("Date:");

        monthbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December", " " }));

        jLabel12.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        jLabel12.setText("Month:");

        yearBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please select", "2022", "2023", "2024", "2025" }));

        year.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        year.setText("Year:");

        peopleField.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        peopleField.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 204, 204), null));
        peopleField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peopleFieldActionPerformed(evt);
            }
        });
        peopleField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                peopleField(evt);
            }
        });

        buttonGroup2.add(BusRB);
        BusRB.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        BusRB.setText("Bus");
        BusRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusRBActionPerformed(evt);
            }
        });

        buttonGroup2.add(trainRB);
        trainRB.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        trainRB.setText("Train");

        buttonGroup2.add(ferryRB);
        ferryRB.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        ferryRB.setText("Ferry");

        buttonGroup2.add(taxiRB);
        taxiRB.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        taxiRB.setText("Taxi");

        buttonGroup2.add(premiumTaxiRB);
        premiumTaxiRB.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        premiumTaxiRB.setText("Premium Taxi");

        jLabel24.setFont(new java.awt.Font("Gill Sans", 1, 14)); // NOI18N
        jLabel24.setText("Step 2");

        jLabel3.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel3.setText("If you would like an Intercity Bus ride, select a city below.");

        buttonGroup2.add(hamiltonRB);
        hamiltonRB.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        hamiltonRB.setText("Hamilton");
        hamiltonRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hamiltonRBActionPerformed(evt);
            }
        });

        buttonGroup2.add(RotoruaRB);
        RotoruaRB.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        RotoruaRB.setText("Rotorua");
        RotoruaRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RotoruaRBActionPerformed(evt);
            }
        });

        buttonGroup2.add(NapierRB);
        NapierRB.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        NapierRB.setText("Napier");
        NapierRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NapierRBActionPerformed(evt);
            }
        });

        buttonGroup2.add(WellingtonRB);
        WellingtonRB.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        WellingtonRB.setText("Wellington");
        WellingtonRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WellingtonRBActionPerformed(evt);
            }
        });

        confirmstep2.setBackground(new java.awt.Color(255, 204, 204));
        confirmstep2.setFont(new java.awt.Font("Monaco", 1, 15)); // NOI18N
        confirmstep2.setText("CONFIRM STEP2");
        confirmstep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmstep2ActionPerformed(evt);
            }
        });

        TotalField.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        TotalField.setText("Total:");

        totalCost.setEditable(false);
        totalCost.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        totalCost.setText("$");
        totalCost.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 204, 204), null));
        totalCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        totalCost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                totalCostpeopleField(evt);
            }
        });

        javax.swing.GroupLayout ptaxiRBLayout = new javax.swing.GroupLayout(ptaxiRB);
        ptaxiRB.setLayout(ptaxiRBLayout);
        ptaxiRBLayout.setHorizontalGroup(
            ptaxiRBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ptaxiRBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ptaxiRBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ptaxiRBLayout.createSequentialGroup()
                        .addGroup(ptaxiRBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ptaxiRBLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(dateBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(monthbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ptaxiRBLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel11)
                                .addGap(65, 65, 65)
                                .addComponent(jLabel12)))
                        .addGap(28, 28, 28)
                        .addGroup(ptaxiRBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ptaxiRBLayout.createSequentialGroup()
                                .addComponent(yearBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(confirmstep2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(ptaxiRBLayout.createSequentialGroup()
                                .addComponent(year)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(totalCost, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13))))
                    .addGroup(ptaxiRBLayout.createSequentialGroup()
                        .addGroup(ptaxiRBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ptaxiRBLayout.createSequentialGroup()
                                .addComponent(BusRB)
                                .addGap(18, 18, 18)
                                .addComponent(trainRB)
                                .addGap(18, 18, 18)
                                .addComponent(ferryRB)
                                .addGap(18, 18, 18)
                                .addComponent(taxiRB)
                                .addGap(18, 18, 18)
                                .addComponent(premiumTaxiRB))
                            .addComponent(jLabel3)
                            .addGroup(ptaxiRBLayout.createSequentialGroup()
                                .addComponent(hamiltonRB)
                                .addGap(18, 18, 18)
                                .addComponent(RotoruaRB)
                                .addGap(18, 18, 18)
                                .addComponent(NapierRB)
                                .addGap(18, 18, 18)
                                .addComponent(WellingtonRB))
                            .addGroup(ptaxiRBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TotalField)
                                .addComponent(jLabel2))
                            .addGroup(ptaxiRBLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(peopleField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ptaxiRBLayout.setVerticalGroup(
            ptaxiRBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ptaxiRBLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(ptaxiRBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BusRB)
                    .addComponent(trainRB)
                    .addComponent(ferryRB)
                    .addComponent(taxiRB)
                    .addComponent(premiumTaxiRB))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(ptaxiRBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hamiltonRB)
                    .addComponent(RotoruaRB)
                    .addComponent(NapierRB)
                    .addComponent(WellingtonRB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ptaxiRBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(peopleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(9, 9, 9)
                .addComponent(TotalField, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(ptaxiRBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(year)
                    .addComponent(totalCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(ptaxiRBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ptaxiRBLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(ptaxiRBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(monthbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ptaxiRBLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(confirmstep2)))
                .addGap(82, 82, 82))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel4.setForeground(new java.awt.Color(255, 204, 102));

        jLabel4.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        jLabel4.setText("Personal Details:");

        jLabel5.setText("FULL NAME:");

        jLabel7.setText("PHONE NO:");

        phoneField.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        phoneField.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 204, 204), null));
        phoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneFieldActionPerformed(evt);
            }
        });
        phoneField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneFieldKeyTyped(evt);
            }
        });

        jLabel8.setText("EMAIL:");

        jLabel23.setFont(new java.awt.Font("Gill Sans", 1, 14)); // NOI18N
        jLabel23.setText("Step 1");

        nameField.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        nameField.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 204, 204), null));
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        ageField.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        ageField.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 204, 204), null));
        ageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageFieldActionPerformed(evt);
            }
        });
        ageField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ageFieldKeyTyped(evt);
            }
        });

        confirmstep1.setBackground(new java.awt.Color(255, 204, 204));
        confirmstep1.setFont(new java.awt.Font("Monaco", 1, 15)); // NOI18N
        confirmstep1.setText("CONFIRM STEP1");
        confirmstep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmstep1(evt);
            }
        });

        jLabel6.setText("AGE:");

        emailField.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        emailField.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 204, 204), null));
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameField)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ageField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confirmstep1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(emailField))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(8, 8, 8)
                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmstep1))
                .addGap(121, 121, 121))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel14.setFont(new java.awt.Font("Monaco", 1, 15)); // NOI18N
        jLabel14.setText("Prices / Fares");

        jLabel16.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        jLabel16.setText("Bus -> $25.00pp");

        jLabel17.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        jLabel17.setText("Train -> $40.00pp");

        jLabel18.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        jLabel18.setText("Ferry -> $50.00pp");

        jLabel19.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        jLabel19.setText("Taxi -> $25.00pp");

        jLabel25.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        jLabel25.setText("Premium Taxi-> $40.00pp");

        jLabel26.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 51, 255));
        jLabel26.setText("In Auckland:");

        jLabel27.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 51, 255));
        jLabel27.setText("Intercity Bus:");

        jLabel28.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        jLabel28.setText("Hamilton -> $30.00pp");

        jLabel29.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        jLabel29.setText("Napier -> $45.00pp");

        jLabel30.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        jLabel30.setText("Rotorua -> $35.00pp");

        jLabel31.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        jLabel31.setText("Wellington -> $50.00pp");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel25)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel28)
                .addGap(7, 7, 7)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 4));

        jLabel20.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        jLabel20.setText("Payment Details:");

        jLabel32.setFont(new java.awt.Font("Gill Sans", 1, 14)); // NOI18N
        jLabel32.setText("Step 3");

        buttonGroup1.add(visaRB);
        visaRB.setText("VISA");
        visaRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visaRBActionPerformed(evt);
            }
        });

        buttonGroup1.add(mastercardRB);
        mastercardRB.setText("Mastercard");
        mastercardRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mastercardRBActionPerformed(evt);
            }
        });

        buttonGroup1.add(aeRB);
        aeRB.setText("American Express");
        aeRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aeRBActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        jLabel15.setText("Cardholder's Name: ");

        jLabel33.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        jLabel33.setText("Card Number:");

        cardNumberField.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        cardNumberField.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 204, 204), null));
        cardNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNumberFieldActionPerformed(evt);
            }
        });
        cardNumberField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cardNumberField(evt);
            }
        });

        cardholdersnameField.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        cardholdersnameField.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 204, 204), null));
        cardholdersnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardholdersnameFieldActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        jLabel34.setText("Card Expiration Date (MM/YY):");

        cardMM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        cardMM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardMMActionPerformed(evt);
            }
        });

        cardYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "22", "23", "24", "25", "26", "27", "28" }));

        jLabel35.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        jLabel35.setText("MM:");

        jLabel36.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        jLabel36.setText("YY:");

        jLabel37.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        jLabel37.setText("CVV:");

        cvvField.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        cvvField.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 204, 204), null));
        cvvField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvvFieldActionPerformed(evt);
            }
        });
        cvvField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cvvField(evt);
            }
        });

        confirmstep3.setBackground(new java.awt.Color(255, 204, 204));
        confirmstep3.setFont(new java.awt.Font("Monaco", 1, 15)); // NOI18N
        confirmstep3.setText("CONFIRM STEP3");
        confirmstep3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmstep3ActionPerformed(evt);
            }
        });

        cvvHelp.setFont(new java.awt.Font("Monaco", 0, 10)); // NOI18N
        cvvHelp.setText("Whats this?");
        cvvHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvvHelpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(visaRB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mastercardRB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(aeRB)
                                .addGap(90, 90, 90))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cardholdersnameField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cardNumberField))
                                .addGap(80, 80, 80))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(cardMM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel36)
                                    .addComponent(cardYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(cvvField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(confirmstep3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel37)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cvvHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap())))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(111, 111, 111)
                                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel35)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(visaRB)
                            .addComponent(mastercardRB)
                            .addComponent(aeRB))))
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(cardholdersnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(cardNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(jLabel36)
                            .addComponent(jLabel37)
                            .addComponent(cvvHelp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cvvField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cardMM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cardYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(confirmstep3)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ptaxiRB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ptaxiRB, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void phoneFieldActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void peopleFieldActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void RestartButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        
        if (evt.getSource() == RestartButton)
        {
            this.dispose();
            new TravelApp();
        }

    }                                             

    private void BusRBActionPerformed(java.awt.event.ActionEvent evt) {                                      

    }                                     

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void ageFieldActionPerformed(java.awt.event.ActionEvent evt) {                                         

    }                                        

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {                                           

        String email = emailField.getText();
        
        String EMAIL_PATTERN = 
             
    "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
    + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        
        if(!email.matches(EMAIL_PATTERN))
        {
          
        }


    }                                          

    private void ageFieldKeyTyped(java.awt.event.KeyEvent evt) {                                  
        char c = evt.getKeyChar();
        if (((c<'0' )|| (c > '9')) && (c != KeyEvent.VK_BACK_SPACE))
        {
             JOptionPane.showMessageDialog(this, "Please input integers only, age cannot be characters");
            evt.consume();
        }
       
    }                                 

    private void hamiltonRBActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void RotoruaRBActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void NapierRBActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void WellingtonRBActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void phoneFieldKeyTyped(java.awt.event.KeyEvent evt) {                                    
        
        
        char c = evt.getKeyChar();
      
        if(phoneField.getText().length() >= 11)
        {
            JOptionPane.showMessageDialog(this, "The phone number cannot have more than 10 digits");
            evt.consume();
        }
        
        if (((c<'0' )|| (c > '9')) && (c != KeyEvent.VK_BACK_SPACE))
        {
             JOptionPane.showMessageDialog(this, "Please input integers only, the number cannot include characters");
             evt.consume();
        }
        
    }                                   

    private void peopleField(java.awt.event.KeyEvent evt) {                             
     char c = evt.getKeyChar();

           if (((c<'0' )|| (c > '9')) && (c != KeyEvent.VK_BACK_SPACE))
        {
             JOptionPane.showMessageDialog(this, "Please input integers only, the number of people cannot include characters");
             evt.consume();
        }
           
            if(peopleField.getText().length() >=3)
        {
            JOptionPane.showMessageDialog(this, "You cannot have more than 999 people per booking");
            evt.consume();
        }
  
    }                            

    private void visaRBActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void mastercardRBActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void aeRBActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void cardNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                

    }                                               

    private void cardholdersnameFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
    }                                                    

    private void cvvHelpActionPerformed(java.awt.event.ActionEvent evt) {                                        
        
            JOptionPane.showMessageDialog(null, "The 3 digits located at the back of your card.","What is a CVV?", JOptionPane.INFORMATION_MESSAGE);

        
    }                                       

    private void cvvField(java.awt.event.KeyEvent evt) {                          
        char c = evt.getKeyChar();

        if(cvvField.getText().length() >= 3)
        {
            JOptionPane.showMessageDialog(this, "The CVV cannot have more than 3 digits");
            evt.consume();
        }

        if (((c<'0' )|| (c > '9')) && (c != KeyEvent.VK_BACK_SPACE))
        {
            JOptionPane.showMessageDialog(this, "Please input integers only, the CVV cannot include characters");
            evt.consume();
        }
    }                         

    private void cvvFieldActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void cardNumberField(java.awt.event.KeyEvent evt) {                                 
           char c = evt.getKeyChar();     
        
        if (((c<'0' )|| (c > '9')) && (c != KeyEvent.VK_BACK_SPACE))
        {
            JOptionPane.showMessageDialog(this, "Please input integers only, the CVV cannot include characters");
            evt.consume();
        }
        
                if(cardNumberField.getText().length() >= 16)
        {
            JOptionPane.showMessageDialog(this, "The card number cannot have more than 16 digits");
            evt.consume();
        }
    }                                

    private void datePerfomed(java.awt.event.ActionEvent evt) {                              
      /* if(dateBox.getSelectedIndex() == 0 && monthbox.getSelectedIndex() >= 4 && yearBox.getSelectedIndex() == 1)
                {
                     JOptionPane.showMessageDialog(this, "Invalid Date");
                }
        else
        {
            
        }
        */
    }                             

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {                                      
       
            
    }                                     

    private void totalCostpeopleField(java.awt.event.KeyEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void cardMMActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void confirmstep1(java.awt.event.ActionEvent evt) {                              
        System.out.println("Personal Details saved to the database");
    }                             

    private void confirmstep2ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        System.out.println("Travel Details saved to the database");
    }                                            

    private void confirmstep3ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        System.out.println("Payment Details saved to the database");
    }                                            

    private void exitButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
               System.out.println("The user has exited the system");
               System.exit(0);
    }                                           

  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TravelApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TravelApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TravelApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TravelApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TravelApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    public javax.swing.JRadioButton BusRB;
    public javax.swing.JRadioButton NapierRB;
    public javax.swing.JButton RestartButton;
    public javax.swing.JRadioButton RotoruaRB;
    private javax.swing.JLabel TotalField;
    public javax.swing.JRadioButton WellingtonRB;
    public javax.swing.JRadioButton aeRB;
    public javax.swing.JTextField ageField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    public javax.swing.JComboBox<String> cardMM;
    public javax.swing.JTextField cardNumberField;
    public javax.swing.JComboBox<String> cardYear;
    public javax.swing.JTextField cardholdersnameField;
    public javax.swing.JButton confirmstep1;
    public javax.swing.JButton confirmstep2;
    public javax.swing.JButton confirmstep3;
    public javax.swing.JPasswordField cvvField;
    public javax.swing.JButton cvvHelp;
    public javax.swing.JComboBox<String> dateBox;
    public javax.swing.JTextField emailField;
    public javax.swing.JButton exitButton1;
    public javax.swing.JRadioButton ferryRB;
    public javax.swing.JRadioButton hamiltonRB;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JProgressBar jProgressBar1;
    public javax.swing.JRadioButton mastercardRB;
    public javax.swing.JComboBox<String> monthbox;
    public javax.swing.JTextField nameField;
    public javax.swing.JTextField peopleField;
    public javax.swing.JTextField phoneField;
    public javax.swing.JRadioButton premiumTaxiRB;
    private javax.swing.JPanel ptaxiRB;
    public javax.swing.JRadioButton taxiRB;
    public javax.swing.JTextField totalCost;
    public javax.swing.JRadioButton trainRB;
    public javax.swing.JRadioButton visaRB;
    private javax.swing.JLabel year;
    public javax.swing.JComboBox<String> yearBox;
    // End of variables declaration                   

   public void addActionListener(ActionListener listener) {
       this.nameField.addActionListener(listener);
       this.phoneField.addActionListener(listener);
       this.emailField.addActionListener(listener);
       this.ageField.addActionListener(listener);
       this.confirmstep1.addActionListener(listener);
       
       this.BusRB.addActionListener(listener);
       this.trainRB.addActionListener(listener);
       this.ferryRB.addActionListener(listener);
       this.taxiRB.addActionListener(listener);
       this.premiumTaxiRB.addActionListener(listener);
       this.confirmstep2.addActionListener(listener);
       
       this.visaRB.addActionListener(listener);
       this.mastercardRB.addActionListener(listener);
       this.aeRB.addActionListener(listener);
       this.cardholdersnameField.addActionListener(listener);
       this.cardNumberField.addActionListener(listener);
       this.cardMM.addActionListener(listener);
       this.cardYear.addActionListener(listener);
       this.confirmstep3.addActionListener(listener);
       
       
       
    }
}
